import type { Product } from "@/types";

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "1",
    name: "Royal Teak Dining Table",
    slug: "royal-teak-dining-table",
    shortDescription: "A stunning 6-seater dining table crafted from premium teak with natural grain finish and hand-carved legs.",
    description: "Premium teak dining table with hand-carved legs.",
    basePrice: 85000,
    sku: "SC-DT-001",
    categoryId: "3",
    categoryName: "Dining Room",
    categorySlug: "dining-room",
    primaryImage: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=700&h=500&fit=crop&auto=format",
    images: [{ id: "1", url: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=700&h=500&fit=crop", isPrimary: true, angle: "FRONT" }],
    isFeatured: true,
    isActive: true,
    manufacturingTime: "20–25 days",
    deliveryTime: "3–5 days",
    warranty: "2 Years",
    rating: 4.8,
    reviewCount: 24,
    availableWoods: [
      { id: "1", name: "Teak",     slug: "teak",     priceModifier: 0,     priceModifierType: "FIXED_ADD" },
      { id: "2", name: "Sheesham", slug: "sheesham", priceModifier: -5000, priceModifierType: "FIXED_ADD" },
      { id: "3", name: "Oak",      slug: "oak",      priceModifier: 8000,  priceModifierType: "FIXED_ADD" },
    ],
  },
  {
    id: "2",
    name: "Heritage Sheesham Wardrobe",
    slug: "heritage-sheesham-wardrobe",
    shortDescription: "Solid sheesham wood 3-door wardrobe with full-length mirror and ample internal storage.",
    description: "Solid sheesham wood 3-door wardrobe.",
    basePrice: 62000,
    sku: "SC-WD-001",
    categoryId: "9",
    categoryName: "Wardrobes",
    categorySlug: "wardrobes",
    primaryImage: "https://images.unsplash.com/photo-1558997519-83ea9252edc8?w=700&h=500&fit=crop&auto=format",
    images: [{ id: "2", url: "https://images.unsplash.com/photo-1558997519-83ea9252edc8?w=700&h=500&fit=crop", isPrimary: true, angle: "FRONT" }],
    isFeatured: true,
    isActive: true,
    manufacturingTime: "25–30 days",
    deliveryTime: "5–7 days",
    warranty: "3 Years",
    rating: 4.6,
    reviewCount: 18,
    availableWoods: [
      { id: "2", name: "Sheesham", slug: "sheesham", priceModifier: 0,     priceModifierType: "FIXED_ADD" },
      { id: "1", name: "Teak",     slug: "teak",     priceModifier: 7000,  priceModifierType: "FIXED_ADD" },
      { id: "5", name: "Plywood",  slug: "plywood",  priceModifier: -8000, priceModifierType: "FIXED_ADD" },
    ],
  },
  {
    id: "3",
    name: "Modern L-Shape Sofa",
    slug: "modern-l-shape-sofa",
    shortDescription: "Plush 5-seater L-shape sofa in premium fabric with solid wood legs and high-density foam.",
    description: "Plush L-shape sofa with premium fabric.",
    basePrice: 72000,
    sku: "SC-SF-001",
    categoryId: "10",
    categoryName: "Sofas",
    categorySlug: "sofas",
    primaryImage: "https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=700&h=500&fit=crop&auto=format",
    images: [{ id: "3", url: "https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=700&h=500&fit=crop", isPrimary: true, angle: "FRONT" }],
    isFeatured: true,
    isActive: true,
    manufacturingTime: "15–20 days",
    deliveryTime: "3–5 days",
    warranty: "1 Year",
    rating: 4.9,
    reviewCount: 41,
    availableWoods: [
      { id: "1", name: "Teak",    slug: "teak",    priceModifier: 0,    priceModifierType: "FIXED_ADD" },
      { id: "3", name: "Oak",     slug: "oak",     priceModifier: 4000, priceModifierType: "FIXED_ADD" },
    ],
  },
  {
    id: "4",
    name: "Executive Office Desk",
    slug: "executive-office-desk",
    shortDescription: "Premium engineered wood office desk with cable management, drawer pedestal, and tempered glass top.",
    description: "Executive office desk with tempered glass top.",
    basePrice: 38000,
    sku: "SC-OD-001",
    categoryId: "4",
    categoryName: "Office",
    categorySlug: "office",
    primaryImage: "https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=700&h=500&fit=crop&auto=format",
    images: [{ id: "4", url: "https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=700&h=500&fit=crop", isPrimary: true, angle: "FRONT" }],
    isFeatured: false,
    isActive: true,
    manufacturingTime: "12–15 days",
    deliveryTime: "2–3 days",
    warranty: "1 Year",
    rating: 4.5,
    reviewCount: 12,
    availableWoods: [
      { id: "6", name: "MDF",              slug: "mdf",              priceModifier: 0,    priceModifierType: "FIXED_ADD" },
      { id: "7", name: "Engineered Wood",  slug: "engineered-wood",  priceModifier: 3000, priceModifierType: "FIXED_ADD" },
      { id: "2", name: "Sheesham",         slug: "sheesham",         priceModifier: 8000, priceModifierType: "FIXED_ADD" },
    ],
  },
  {
    id: "5",
    name: "Rajwada Wooden Bed",
    slug: "rajwada-wooden-bed",
    shortDescription: "Handcrafted king-size bed with intricate carving, upholstered headboard, and hydraulic storage.",
    description: "Handcrafted king-size bed with intricate carving.",
    basePrice: 95000,
    sku: "SC-BD-001",
    categoryId: "11",
    categoryName: "Beds",
    categorySlug: "beds",
    primaryImage: "https://images.unsplash.com/photo-1505693314120-0d443867891c?w=700&h=500&fit=crop&auto=format",
    images: [{ id: "5", url: "https://images.unsplash.com/photo-1505693314120-0d443867891c?w=700&h=500&fit=crop", isPrimary: true, angle: "FRONT" }],
    isFeatured: true,
    isActive: true,
    manufacturingTime: "30–35 days",
    deliveryTime: "5–7 days",
    warranty: "3 Years",
    rating: 4.9,
    reviewCount: 33,
    availableWoods: [
      { id: "1", name: "Teak",     slug: "teak",     priceModifier: 0,     priceModifierType: "FIXED_ADD" },
      { id: "4", name: "Mahogany", slug: "mahogany", priceModifier: 10000, priceModifierType: "FIXED_ADD" },
      { id: "2", name: "Sheesham", slug: "sheesham", priceModifier: -6000, priceModifierType: "FIXED_ADD" },
    ],
  },
  {
    id: "6",
    name: "Walnut Coffee Table",
    slug: "walnut-coffee-table",
    shortDescription: "Minimalist walnut-finish coffee table with tempered glass top and lower open shelf for storage.",
    description: "Minimalist walnut-finish coffee table.",
    basePrice: 18500,
    sku: "SC-CT-001",
    categoryId: "13",
    categoryName: "Coffee Tables",
    categorySlug: "coffee-tables",
    primaryImage: "https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?w=700&h=500&fit=crop&auto=format",
    images: [{ id: "6", url: "https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?w=700&h=500&fit=crop", isPrimary: true, angle: "FRONT" }],
    isFeatured: false,
    isActive: true,
    manufacturingTime: "10–12 days",
    deliveryTime: "2–3 days",
    warranty: "1 Year",
    rating: 4.4,
    reviewCount: 9,
    availableWoods: [
      { id: "2", name: "Sheesham",        slug: "sheesham",        priceModifier: 0,    priceModifierType: "FIXED_ADD" },
      { id: "7", name: "Engineered Wood", slug: "engineered-wood", priceModifier: -2000, priceModifierType: "FIXED_ADD" },
    ],
  },
  {
    id: "7",
    name: "Floating TV Unit",
    slug: "floating-tv-unit",
    shortDescription: "Contemporary wall-mounted TV unit with acrylic shutters, LED groove, and ample cable management.",
    description: "Contemporary wall-mounted TV unit.",
    basePrice: 28000,
    sku: "SC-TV-001",
    categoryId: "8",
    categoryName: "TV Units",
    categorySlug: "tv-units",
    primaryImage: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=700&h=500&fit=crop&auto=format",
    images: [{ id: "7", url: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=700&h=500&fit=crop", isPrimary: true, angle: "FRONT" }],
    isFeatured: false,
    isActive: true,
    manufacturingTime: "12–15 days",
    deliveryTime: "3–4 days",
    warranty: "1 Year",
    rating: 4.7,
    reviewCount: 27,
    availableWoods: [
      { id: "6", name: "MDF",             slug: "mdf",             priceModifier: 0,    priceModifierType: "FIXED_ADD" },
      { id: "5", name: "Plywood",         slug: "plywood",         priceModifier: 2000, priceModifierType: "FIXED_ADD" },
    ],
  },
  {
    id: "8",
    name: "Kids Study Bunk Bed",
    slug: "kids-study-bunk-bed",
    shortDescription: "Space-saving bunk bed with integrated study desk, bookshelf, and safety guardrails.",
    description: "Space-saving bunk bed with integrated study desk.",
    basePrice: 42000,
    sku: "SC-KB-001",
    categoryId: "7",
    categoryName: "Kids Room",
    categorySlug: "kids",
    primaryImage: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=700&h=500&fit=crop&auto=format",
    images: [{ id: "8", url: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=700&h=500&fit=crop", isPrimary: true, angle: "FRONT" }],
    isFeatured: false,
    isActive: true,
    manufacturingTime: "20–25 days",
    deliveryTime: "4–5 days",
    warranty: "2 Years",
    rating: 4.6,
    reviewCount: 15,
    availableWoods: [
      { id: "5", name: "Plywood", slug: "plywood", priceModifier: 0,    priceModifierType: "FIXED_ADD" },
      { id: "2", name: "Sheesham", slug: "sheesham", priceModifier: 6000, priceModifierType: "FIXED_ADD" },
    ],
  },
  {
    id: "9",
    name: "Garden Teak Bench",
    slug: "garden-teak-bench",
    shortDescription: "Weather-resistant outdoor bench in solid teak with natural oil finish. Built to last decades.",
    description: "Weather-resistant outdoor bench in solid teak.",
    basePrice: 24000,
    sku: "SC-OB-001",
    categoryId: "5",
    categoryName: "Outdoor",
    categorySlug: "outdoor",
    primaryImage: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=700&h=500&fit=crop&auto=format",
    images: [{ id: "9", url: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=700&h=500&fit=crop", isPrimary: true, angle: "FRONT" }],
    isFeatured: false,
    isActive: true,
    manufacturingTime: "10–12 days",
    deliveryTime: "3–4 days",
    warranty: "5 Years",
    rating: 4.8,
    reviewCount: 7,
    availableWoods: [
      { id: "1", name: "Teak", slug: "teak", priceModifier: 0, priceModifierType: "FIXED_ADD" },
    ],
  },
];
